- name: Demo on condition
  hosts: localhost
  tasks:
    - name: print apple price
      ansible.builtin.debug:
        msg: Apple price - 1$
      when: The fruit == "Apple"

    - name: print orange price
      ansible.builtin.debug:
        msg: Apple price - 2$
      when: The fruit == "orange"